# Generated by Django 2.1.4 on 2018-12-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodespesa',
            name='year_in_tipodespesa',
            field=models.CharField(choices=[('Remedio', 'Remedio'), ('Roupas', 'Roupas'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], default='Remedio', max_length=2),
        ),
    ]
