# Generated by Django 2.1.4 on 2018-12-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0002_tipodespesa_year_in_tipodespesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Boleto', 'Boleto')], default='Dinheiro', max_length=2)),
            ],
        ),
    ]
